disabled_rules: # rule identifiers to exclude from running
- type_body_length
- file_length
- line_length
- variable_name
- cyclomatic_complexity
- function_body_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods